[package]
name = "cuddlyfs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
env_logger = "0.11.5"
log = "0.4.22"
md5 = "0.7.0"
tokio = { version = "1", features = ["full"] }
tonic = "0.12.2"
