services:
    namenode:
        build:
            context: .
            dockerfile: Dockerfile.namenode
            target: final
        container_name: cuddlyfs_namenode
        network_mode: "host"
        environment:
            # corresponds to config/docker.yaml
            - RUN_MODE=docker
            - PORT=50051

    datanode1:
        build:
            context: .
            dockerfile: Dockerfile.datanode
        container_name: cuddlyfs_datanode1
        network_mode: "host"
        depends_on:
            - namenode
        environment:
            - RUN_MODE=docker
            - PORT=50052

    datanode2:
        build:
            context: .
            dockerfile: Dockerfile.datanode
        container_name: cuddlyfs_datanode2
        network_mode: "host"
        depends_on:
            - namenode
        environment:
            - RUN_MODE=docker
            - PORT=50053

    datanode3:
        build:
            context: .
            dockerfile: Dockerfile.datanode
        container_name: cuddlyfs_datanode3
        network_mode: "host"
        depends_on:
            - namenode
        environment:
            - RUN_MODE=docker
            - PORT=50054
