services:
    namenode:
        build:
            context: .
            dockerfile: Dockerfile.namenode
            target: final
        container_name: cuddlyfs_namenode
        ports:
            - 0.0.0.0:50051:50051
        networks:
            - cuddlyfs_network
        environment:
            # corresponds to config/docker.yaml
            - RUN_MODE=docker
            - PORT=50051

    datanode1:
        build:
            context: .
            dockerfile: Dockerfile.datanode
        container_name: cuddlyfs_datanode1
        ports:
            - 0.0.0.0:50052:50052
            - 0.0.0.0:60052:60052
        networks:
            - cuddlyfs_network
        depends_on:
            - namenode
        environment:
            - RUN_MODE=docker
            - PORT=50052

    datanode2:
        build:
            context: .
            dockerfile: Dockerfile.datanode
        container_name: cuddlyfs_datanode2
        ports:
            - 0.0.0.0:50053:50053
            - 0.0.0.0:60053:60053
        networks:
            - cuddlyfs_network
        depends_on:
            - namenode
        environment:
            - RUN_MODE=docker
            - PORT=50053

    datanode3:
        build:
            context: .
            dockerfile: Dockerfile.datanode
        container_name: cuddlyfs_datanode3
        ports:
            - 0.0.0.0:50054:50054
            - 0.0.0.0:60054:60054
        networks:
            - cuddlyfs_network
        depends_on:
            - namenode
        environment:
            - RUN_MODE=docker
            - PORT=50054

networks:
    cuddlyfs_network:
        driver: bridge
