debug: true

namenode:
    bind_address: "[::1]:50051"
    name_dir: "/tmp/cuddlyfs/namenode"

datanode:
    namenode_rpc_address: "http://192.168.65.9:50051"
    data_dir: "/tmp/cuddlyfs/datanode"
    disk_check_interval: 3000

xfer_port: 50010
packet_size: 65536
block_size: 67108864
replication_factor: 3
